/**
 * POST /approve-prd - Approve or reject a PRD generated by PM Agent
 *
 * This endpoint handles user actions on PRDs:
 * - approve: Emit event to transition to approved state (triggers ProjM decomposition)
 * - reject: Mark feature as rejected, remove from workflow
 * - discuss: Open feedback discussion (v2 feature, not yet implemented)
 */

import type { Request, Response } from 'express';
import type { EventEmitter } from '../../../lib/events.js';
import type { FeatureLoader } from '../../../services/feature-loader.js';
import { getErrorMessage, logError } from '../common.js';

export function createApprovePRDHandler(events: EventEmitter, featureLoader: FeatureLoader) {
  return async (req: Request, res: Response): Promise<void> => {
    try {
      const { projectPath, featureId, action, feedback } = req.body as {
        projectPath: string;
        featureId: string;
        action: 'approve' | 'reject' | 'discuss';
        feedback?: string;
      };

      if (!projectPath) {
        res.status(400).json({ success: false, error: 'projectPath is required' });
        return;
      }

      if (!featureId) {
        res.status(400).json({ success: false, error: 'featureId is required' });
        return;
      }

      if (!action) {
        res.status(400).json({ success: false, error: 'action is required' });
        return;
      }

      if (!['approve', 'reject', 'discuss'].includes(action)) {
        res
          .status(400)
          .json({ success: false, error: 'action must be approve, reject, or discuss' });
        return;
      }

      // Load feature to verify it exists and is in correct state
      const feature = await featureLoader.get(projectPath, featureId);

      if (!feature) {
        res.status(404).json({ success: false, error: 'Feature not found' });
        return;
      }

      if (feature.workItemState !== 'prd_ready') {
        res.status(400).json({
          success: false,
          error: `Feature is not in prd_ready state (current: ${feature.workItemState})`,
        });
        return;
      }

      switch (action) {
        case 'approve':
          // Emit event for PM Agent to handle approval
          events.emit('ideation:prd-approved', {
            projectPath,
            featureId,
          });
          res.json({ success: true, message: 'PRD approved - breaking down into epics...' });
          break;

        case 'reject':
          // Update feature to rejected state
          await featureLoader.update(projectPath, featureId, {
            workItemState: 'rejected',
            status: 'backlog', // Keep on board but marked as rejected
          });

          events.emit('ideation:prd-rejected', {
            projectPath,
            featureId,
            feedback,
          });

          res.json({ success: true, message: 'PRD rejected' });
          break;

        case 'discuss':
          // v2 feature - not yet implemented
          res.status(501).json({
            success: false,
            error: 'Discussion flow not yet implemented',
          });
          break;

        default:
          res.status(400).json({ success: false, error: 'Invalid action' });
      }
    } catch (error) {
      logError(error, 'Approve PRD failed');
      res.status(500).json({ success: false, error: getErrorMessage(error) });
    }
  };
}
