/**
 * Gamification types for homeMaker — XP, levels, achievements, streaks, quests,
 * and home health scoring.
 */

/** A single achievement that has been earned by the user */
export interface EarnedAchievement {
  id: string;
  unlockedAt: string;
  seen: boolean;
}

/** Streak state for a particular tracked activity */
export interface StreakState {
  current: number;
  best: number;
  lastCompletedAt: string | null;
}

/** Per-month streak state (budget streaks track month strings, not dates) */
export interface MonthlyStreakState {
  current: number;
  best: number;
  lastMonth: string | null;
}

/** Home health score broken down by pillar (each pillar 0-25, total 0-100) */
export interface HomeHealthScore {
  total: number;
  maintenance: number;
  inventory: number;
  budget: number;
  systems: number;
  calculatedAt: string;
}

/** Full gamification profile for the household */
export interface GamificationProfile {
  xp: number;
  level: number;
  levelTitle: string;
  xpToNextLevel: number;
  achievements: EarnedAchievement[];
  streaks: {
    maintenance: StreakState;
    budget: MonthlyStreakState;
  };
  homeHealthScore: HomeHealthScore;
}

/** Achievement category for grouping and filtering */
export type AchievementCategory =
  | 'maintenance'
  | 'inventory'
  | 'budget'
  | 'onboarding'
  | 'seasonal'
  | 'secret';

/** Definition of a single achievement (static catalog) */
export interface AchievementDefinition {
  id: string;
  title: string;
  description: string;
  icon: string;
  xpReward: number;
  category: AchievementCategory;
}

/** Achievement definition with earned status attached (for API response) */
export interface AchievementWithStatus extends AchievementDefinition {
  earned: boolean;
  unlockedAt: string | null;
  seen: boolean;
}

/** A single XP event recorded to xp_history */
export interface XpEvent {
  source: string;
  amount: number;
  multiplier: number;
  timestamp: string;
}

/** A quest — short-term goal generated by system or Ava */
export interface Quest {
  id: string;
  title: string;
  description: string;
  xpReward: number;
  progress: number;
  target: number;
  category: string;
  expiresAt?: string;
  generatedBy: 'system' | 'ava';
}

/** Result returned from awardXp() */
export interface XpAwardResult {
  xpGained: number;
  newTotal: number;
  leveledUp: boolean;
  newLevel: number;
  newTitle: string;
}
